
import "./globals.css";
import NavBar from "./components/particles/NavBar";
import Button from "./components/atoms/Button";





export const metadata = {
  title: "Olivia ShowRoom",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <Button />
        {children}
      </body>
    </html>
  );
}
