
import "./globals.css";
import NavBar from "./components/particles/navBar";




export const metadata = {
  title: "Olivia ShowRoom",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
